repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v10.0.0-rc.1
    hooks:
      - id: eslint
        name: Frontend ESLint
        language: node
        entry: bash -c "cd frontend && npm run lint"
        files: ^frontend/.*\.(js|jsx|ts|tsx)$
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: Prettier frontend
        language: node
        entry: bash -c "cd frontend && npm run format"
        files: ^frontend/.*\.(js|jsx|ts|tsx|css|json|md)$
        pass_filenames: false
